export interface Faq {
  q: string;
  a: string;
  tag: string;
}
/** Plain-language help. Nothing here promises timelines or live agency connections the prototype does not have. */
export const faqs: Faq[] = [
  {
    tag: "Getting started",
    q: "What is LASBAG?",
    a: "LASBAG is one place to start and follow your building approval. You describe your project, LASBAG works out which documents you need, and you track every stage in one journey. It doesn't replace any agency: each agency still makes its own decisions.",
  },
  {
    tag: "Getting started",
    q: "How do I start an application?",
    a: "Create an account or sign in, choose New application, and answer a few short questions about your building. Your personalised checklist builds as you answer.",
  },
  {
    tag: "Getting started",
    q: "What is LASBAG AI, and who can use it?",
    a: "LASBAG AI is a guided requirements assistant, not an open-ended chatbot. Applicants and building professionals can open New application from the navigation, answer six questions about the project, and get a checklist generated by LASBAG's rules engine. Sign in or create an account first.",
  },
  {
    tag: "Getting started",
    q: "Do I need to know which agencies are involved?",
    a: "No. LASBAG works out which agencies need to review your application and coordinates them for you.",
  },
  {
    tag: "Documents",
    q: "Which files can I upload?",
    a: "PDF, PNG and JPG files, up to 10 MB each. If a file is larger, compress it or split it into parts.",
  },
  {
    tag: "Documents",
    q: "What if I upload the wrong document?",
    a: "Upload the right one again. LASBAG keeps the earlier version on record and uses the newest.",
  },
  {
    tag: "Documents",
    q: "Who can see my documents?",
    a: "You, and the agencies that need to review your application. Nobody else can open them.",
  },
  {
    tag: "Tracking",
    q: "How do I see where my application is?",
    a: "Your dashboard shows your seven-stage journey, your next required action and which agencies are involved. You can also use Track application with your reference number, which shows the stage and progress only.",
  },
  {
    tag: "Tracking",
    q: "What does 'Action needed' mean?",
    a: "An agency needs something more from you, such as a clearer document. Only that item is affected. You don't need to restart your application, and your reason and next step are shown on your dashboard.",
  },
  {
    tag: "Tracking",
    q: "How long will each stage take?",
    a: "Each request shows a target response time on your dashboard. These are targets, not guarantees, and they can change if an agency needs more information.",
  },
  {
    tag: "Account",
    q: "Can a professional apply for a client?",
    a: "Yes. Register as a Professional (architect, engineer, surveyor or planner) to prepare and follow applications.",
  },
  {
    tag: "About this service",
    q: "Is this connected to live government systems?",
    a: "This is a prototype that uses sample data. Nothing you see here is a real approval, and it isn't connected to live agency systems.",
  },
];
